### ISSUE TITLE
abs url for kennishub icon

### ISSUE THREAD

**Issue by plenaerts** [Agentschap-Binnenlands-Bestuur/vloca-portal#1]
https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/blob/dev/_sass/vloca-2020/_crosslink.scss#L34 contains an absolute path.

I think this may be the solution: https://stackoverflow.com/questions/20037266/how-to-use-jekyll-baseurl-in-css-files

**Comment by uxmento** [comment]
This issue should be fixed on dev branch.
