### ISSUE TITLE
Diverse aanpassingen

### ISSUE THREAD

**Issue by bertvananderoye** [Agentschap-Binnenlands-Bestuur/vloca-portal#13]
**Frontpage:**

- "Meer weten over kennishub" -> link niet correct + target _blank zetten
- "Waarom zijn gedeelde afspraken nodig? Waarom is standaardisatie nodig?"
-> Linktekst "Meer info over OSLO op overheid.vlaanderen.be" target _blank zetten

**Nieuwsoverzicht:**

- Link naar 'contacteer ons' klopt niet (onderaan de pagina).

**Nieuwsitems:**

- https://vloca.vlaanderen.be/nieuws/registratie_werksessies/
   ->grote afbeelding weg doen. Duwt belangrijke content naar onder.
   -> Werksessie 2: linktekst "Schrijf je in" + target _blank zetten

- https://vloca.vlaanderen.be/nieuws/imec_vloca_post/
   -> Linktekst "Lees de verhelderende blogpost" + target _blank zetten

- https://vloca.vlaanderen.be/nieuws/vloca-van-start/
   -> eindpunt achter laatste zin

- https://vloca.vlaanderen.be/nieuws/herbeleef-het-online-vloca-infomoment/
   -> Linktekst "De werkwijze van het VLOCA co-creatie proces (pdf)" moet worden "Bekijk de presentatie (pdf)"

**Comment by plenaerts** [comment]
@bertvananderoye neem jij die zelf op? ik heb er todo's van gemaakt:

### Frontpage:
- [x] "Meer weten over kennishub" -> link niet correct + target _blank zetten
- [x] "Waarom zijn gedeelde afspraken nodig? Waarom is standaardisatie nodig?"
- [x] Linktekst "Meer info over OSLO op overheid.vlaanderen.be" target _blank zetten

### Nieuwsitems:
https://vloca.vlaanderen.be/nieuws/registratie_werksessies/
- [x] ->grote afbeelding weg doen. Duwt belangrijke content naar onder.
- [x] -> Werksessie 2: linktekst "Schrijf je in" + target _blank zetten

https://vloca.vlaanderen.be/nieuws/imec_vloca_post/
- [x] -> Linktekst "Lees de verhelderende blogpost" + target _blank zetten

https://vloca.vlaanderen.be/nieuws/vloca-van-start/
- [x] -> eindpunt achter laatste zin

https://vloca.vlaanderen.be/nieuws/herbeleef-het-online-vloca-infomoment/
- [x] -> Linktekst "De werkwijze van het VLOCA co-creatie proces (pdf)" moet worden "Bekijk de presentatie (pdf)"

**Comment by bertvananderoye** [comment]
Handig! Ik neem verder op.
