### ISSUE TITLE
Werking kennishub Nieuwsbericht

### ISSUE THREAD

**Issue by SanderKnapen** [Agentschap-Binnenlands-Bestuur/vloca-portal#17]
We zouden een nieuwsbericht willen plaatsen met het filmpje van Stefan over de werking van de kennishub.
Het nieuwsbericht kan je in het word doc. in bijlage terugvinden.
De link naar het filmpje op Youtube staat mee in het nieuwsbericht.

[Nieuwsbericht werking Kennishub.docx](https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/files/4868974/Nieuwsbericht.werking.Kennishub.docx)

**Comment by plenaerts** [comment]
Sander, nieuwsberichten hebben altijd volgende nodig:
* datum
* titel
* thumbnail
* teaser tekst die je in het overzicht ziet
* intro die je bovenaan het nieuwsbericht ziet in grote font
* categorie(ën) waarmee je kan filteren.

![SharedScreenshot](https://user-images.githubusercontent.com/14309550/87679912-0d86d100-c77d-11ea-9a06-7499d91e1efc.jpg)

**Comment by SanderKnapen** [comment]
Bedankt voor de feedback.
Onderaan het word doc. "Nieuwsbericht werking Kennishub 2.0" heb ik deze puntjes mee opgenomen en beantwoord.
De thumbnail zit mee in bijlage bij deze post.

![Thumbnail](https://user-images.githubusercontent.com/66820818/87682123-c2ba8880-c77f-11ea-940c-d8af554fbfad.jpg)
[Nieuwsbericht werking Kennishub 2.0.docx](https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/files/4932017/Nieuwsbericht.werking.Kennishub.2.0.docx)
