### ISSUE TITLE
Nieuwsbericht VLOCA trajecten 

### ISSUE THREAD

**Issue by Annelien1** [Agentschap-Binnenlands-Bestuur/vloca-portal#22]
[Tekst_VLOCAtrajecten_portaal.docx](https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/files/5406388/Tekst_VLOCAtrajecten_portaal.docx)

**Comment by FJanssen74** [comment]
nieuw nieuwsitem aangemaakt
unordered lists toegevoegd
twee images opgeladen (full size en thumb)
Annelien heeft zelf ook enkele aanpassingen gedaan, kwestie van het systeem te leren kennen
