### ISSUE TITLE
Contacteer ons - wijzigen

### ISSUE THREAD

**Issue by KDaems** [Agentschap-Binnenlands-Bestuur/vloca-portal#6]
Tabblad 'contacteer ons' moet redirect naar http://stedenbeleid.vlaanderen.be/vloca-contactformulier zijn. 

'Contacteer ons' rechtsboven in header moet mail vloca@vlaanderen.be ipv stedenbeleid.

Onderaan startpagina ook mailadres veranderen naar vloca@vlaanderen.be

**Comment by plenaerts** [comment]
@KDaems : staat alle nodige info op contactformulier stedenbeleid? Zoja, dan kunnen we een link maken in het navigatiemenu ipv het tabblad.

Rechtsboven en rechtsonder moet via aanvraag naar AIV. Die zitten in onze "global header". Dit kunnen we al doen.

Tabblad contacteer ons zit nu in een aparte pagina, waardoor die automatisch door includes/navigation.html wordt opgepikt. De contact page moet eruit en we moeten manueel die link toevoegen in navigation.html. mobile navigation na te kijken. Pas uit te voeren na bevestiging door @KDaems
