### ISSUE TITLE
FAQ item

### ISSUE THREAD

**Issue by KDaems** [Agentschap-Binnenlands-Bestuur/vloca-portal#7]
tekst in bijlage invoegen als Veelgestelde vraag.
[FAQ VLOCA.docx](https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/files/4782568/FAQ.VLOCA.docx)

**Comment by KDaems** [comment]
Ook deze faq is moeite waard.
[VLOCA - FAQ - waarom gedeelde afspraken.docx](https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/files/4782600/VLOCA.-.FAQ.-.waarom.gedeelde.afspraken.docx)

**Comment by plenaerts** [comment]
Deze moeten voorlopig hardcoded in index.html vanaf lijn 201. Als https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/issues/2 in orde is gaan we het herwerken naar dynamische FAQ's, maar for now quick and dirty in index.html.

**Comment by plenaerts** [comment]
staat vanaf ong 14u30 klaar op test
