### ISSUE TITLE
Nieuwsitems

### ISSUE THREAD

**Issue by KDaems** [Agentschap-Binnenlands-Bestuur/vloca-portal#8]
Drie nieuwsitems/blogposts om in te geven.
[Nieuwsitems_websiteVLOCA.docx](https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/files/4782577/Nieuwsitems_websiteVLOCA.docx)

**Comment by plenaerts** [comment]
Deze moeten in _posts
