### ISSUE TITLE
Nieuwsitem infomoment VLOCA

### ISSUE THREAD

**Issue by SanderKnapen** [Agentschap-Binnenlands-Bestuur/vloca-portal#9]
In word doc. een nieuwsitem over het VLOCA infomoment.
In de mailchimp voor de nazorg zullen we ook naar deze pagina verwijzen voor de presentaties en de video's
Kunnen de video's en presentaties op deze pagina worden opgeladen? Deze zijn via deze link te vinden op mijn Onedrive: https://vlaamseoverheid-my.sharepoint.com/:f:/g/personal/sander_knapen_vlaanderen_be/Eg6IWn7wELBDk4-3yJ7Z_zYBWsOj35U03WC9jP5xqOhRZQ?e=dUv4GM

**Comment by plenaerts** [comment]
@SanderKnapen  ik zie geen word doc.

@bertvananderoye kan jij die video's op youtube zetten aub? Meer details bij @SanderKnapen  en @Annelien1

**Comment by SanderKnapen** [comment]
@plenaerts Oei, iets misgelopen dan. Sorry. Nu wel gelukt?

https://vlaamseoverheid-my.sharepoint.com/:w:/g/personal/sander_knapen_vlaanderen_be/EcfqBN_1X6BPtluVLr6p27MBa0IN3wxMyc5xZbuTzVGmLQ?e=lIwOsH

**Comment by bertvananderoye** [comment]
Hierbij nieuwsitem infomoment in HTML. Link naar opname op YouTube is gelegd. Link naar presentaties nog niet.

[nieuwsitem_infomoment_vloca.txt](https://github.com/Agentschap-Binnenlands-Bestuur/vloca-portal/files/4811686/nieuwsitem_infomoment_vloca.txt)

**Comment by plenaerts** [comment]
@bertvananderoye kan je dat in dir _posts aanmaken met juiste styling? Zie andere voorbeelden, evt ook in branch "ux"

**Comment by bertvananderoye** [comment]
Ik zal proberen. Kunnen de presentaties ook ergens geüpload worden?

**Comment by Annelien1** [comment]
Presentaties zijn te vinden op onedrive Sander: https://vlaamseoverheid-my.sharepoint.com/:f:/g/personal/sander_knapen_vlaanderen_be/Eg6IWn7wELBDk4-3yJ7Z_zYBWsOj35U03WC9jP5xqOhRZQ?e=dUv4GM

**Comment by bertvananderoye** [comment]
Bedankt. Hoe gebeurt de upload naar de portaalsite?
